#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/masterkorp/.Xmodmap"

# Start the dropbox daemon
dropboxd




exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/masterkorp/.fluxbox/log"
