#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.
# All apps need to have the "&" to stay in the background 

# Change your keymap:
xmodmap "/home/masterkorp/.Xmodmap"

# Start the dropbox daemon
dropboxd & 

# Start conky
conky &


exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/masterkorp/.fluxbox/log"
